// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf3M3pWUsZ7-uN_we5N5ApGFpXErYjhJc',
    appId: '1:640720908106:web:166c98219ce1ce7c049bb3',
    messagingSenderId: '640720908106',
    projectId: 'gracefood-2024',
    authDomain: 'gracefood-2024.firebaseapp.com',
    storageBucket: 'gracefood-2024.appspot.com',
    measurementId: 'G-L4BYGCZ0LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfUSZJrk-j9yGQaxWIUbeULctDi6ImH6E',
    appId: '1:640720908106:android:a2f58b7ec530a430049bb3',
    messagingSenderId: '640720908106',
    projectId: 'gracefood-2024',
    storageBucket: 'gracefood-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgH4snvmVY4fHSSId08oZ0gQF72-pdsa8',
    appId: '1:640720908106:ios:1e5a692720f0a681049bb3',
    messagingSenderId: '640720908106',
    projectId: 'gracefood-2024',
    storageBucket: 'gracefood-2024.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgH4snvmVY4fHSSId08oZ0gQF72-pdsa8',
    appId: '1:640720908106:ios:1e5a692720f0a681049bb3',
    messagingSenderId: '640720908106',
    projectId: 'gracefood-2024',
    storageBucket: 'gracefood-2024.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf3M3pWUsZ7-uN_we5N5ApGFpXErYjhJc',
    appId: '1:640720908106:web:acf4c739459ea28d049bb3',
    messagingSenderId: '640720908106',
    projectId: 'gracefood-2024',
    authDomain: 'gracefood-2024.firebaseapp.com',
    storageBucket: 'gracefood-2024.appspot.com',
    measurementId: 'G-1PFEY236Z1',
  );
}
